In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentc = ['the glass of milk',
         'the glass of juice',
         'the cup of tea',
         'I am a good boy',
         'I am a good developer',
         'understand the meaning of words',
         'your videos are good'
]
sentc

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
voc_size = 10000    # defining the vocabulary size

In [4]:
## One hot representation
one_hot_repr = [one_hot(words, voc_size) for words in sentc]
one_hot_repr

[[3046, 7069, 6100, 5233],
 [3046, 7069, 6100, 6508],
 [3046, 9583, 6100, 719],
 [1275, 1285, 8254, 7594, 2484],
 [1275, 1285, 8254, 7594, 2364],
 [1232, 3046, 3330, 6100, 7560],
 [5580, 3815, 3137, 7594]]

In [6]:
## word embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
senc_len = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=senc_len)
print(embedded_docs)

[[   0    0    0    0 3046 7069 6100 5233]
 [   0    0    0    0 3046 7069 6100 6508]
 [   0    0    0    0 3046 9583 6100  719]
 [   0    0    0 1275 1285 8254 7594 2484]
 [   0    0    0 1275 1285 8254 7594 2364]
 [   0    0    0 1232 3046 3330 6100 7560]
 [   0    0    0    0 5580 3815 3137 7594]]


In [8]:
## Feature representation

dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = senc_len))
model.compile('adam', 'mse')

/home/jeswin/projects/tf_cuda/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
I0000 00:00:1741334853.172692    5821 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1768 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

I0000 00:00:1741334947.902436    9136 service.cc:148] XLA service 0x7f5f28014180 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1741334947.903202    9136 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 3050 Laptop GPU, Compute Capability 8.6
I0000 00:00:1741334947.930573    9136 cuda_dnn.cc:529] Loaded cuDNN version 90300


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 414ms/step


I0000 00:00:1741334948.148626    9136 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


array([[[-1.21483915e-02, -4.10959832e-02,  3.94020341e-02,
          4.68560569e-02, -2.78462656e-02,  4.58188914e-02,
         -2.08564401e-02, -4.03447375e-02, -2.02513468e-02,
         -2.93686148e-02],
        [-1.21483915e-02, -4.10959832e-02,  3.94020341e-02,
          4.68560569e-02, -2.78462656e-02,  4.58188914e-02,
         -2.08564401e-02, -4.03447375e-02, -2.02513468e-02,
         -2.93686148e-02],
        [-1.21483915e-02, -4.10959832e-02,  3.94020341e-02,
          4.68560569e-02, -2.78462656e-02,  4.58188914e-02,
         -2.08564401e-02, -4.03447375e-02, -2.02513468e-02,
         -2.93686148e-02],
        [-1.21483915e-02, -4.10959832e-02,  3.94020341e-02,
          4.68560569e-02, -2.78462656e-02,  4.58188914e-02,
         -2.08564401e-02, -4.03447375e-02, -2.02513468e-02,
         -2.93686148e-02],
        [-7.55608082e-04, -3.45382579e-02,  4.33264486e-02,
          1.79093219e-02, -2.96797398e-02, -7.28201866e-03,
          2.52579935e-02,  3.79233994e-02,  7.520664